<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArray($ids_array){
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.id in (:ids_array)')
            ->setParameter('ids_array', $ids_array);

        return $qb->getQuery()->getResult();
    }

    public function findByCategory($id){
        $qb = $this->createQueryBuilder('p')
                ->select('p')
                ->where('p.categorie = :categorie')
                ->andWhere('p.disponible = 1')
                ->orderBy('p.id')
                ->setParameter('categorie', $id);

        return $qb->getQuery()->getResult();
    }

    public function recherche($chaine)
    {
        $qb =$this->createQueryBuilder('p')
                ->select('p')
                ->where('p.nom like :chaine')
                ->andWhere('p.disponible = 1')
                ->orderBy('p.id')
                ->setParameter('chaine', '%'.$chaine.'%');

        return $qb->getQuery()->getResult();
    }
}
